# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "../releases/", "/releases"

  config.vm.define "v32" do |v32|
    v32.vm.box = "ubuntu/trusty32"
  end

  config.vm.define "v64" do |v64|
    v64.vm.box = "ubuntu/trusty64"
  end
end
