#!/bin/sh

# start Dropbear, with the keys under /run
echo -n "Starting Dropbear ..."

mkdir /run/dropbear
for i in rsa dss
do
	dropbearkey -t $i -f /run/dropbear/${i}_key > /dev/null 2>&1
done
dropbear -d /run/dropbear/dss_key -r /run/dropbear/rsa_key

echo " done."