#!/bin/sh

case "$1" in
	start)
		echo -n "Configuring networking ..."

		# set up a loopback interface
		ifconfig lo 127.0.0.1 up
		route add -net 127.0.0.0 netmask 255.0.0.0 dev lo

		# turn on the wireless interface
		ifconfig wlan0 up

		if [ -f /etc/wpa_supplicant.conf ]
		then
			# run wpa_supplicant
			wpa_supplicant -B \
			               -iwlan0 \
			               -c/etc/wpa_supplicant.conf \
			               -P/run/wpa_supplicant.pid

			# run dhcpcd
			dhcpcd -L wlan0
		fi

		echo " done."
		;;

	stop)
		if [ -f /run/wpa_supplicant.pid ]
		then
			# stop dhcpcd
			dhcpcd -k wlan0

			# stop wpa_supplicant
			kill $(cat /run/wpa_supplicant.pid)
			rm /run/wpa_supplicant.conf
		fi

		# bring down the wireless interface
		ifconfig wlan0 down

		# disable the loopback interface
		ifconfig lo down
		;;
esac
