#!/bin/dash

# set the executable search path
export PATH="/bin"

# mount virtual file systems
echo -n "Mounting virtual file systems ..."

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
mount -t tmpfs run /run
mount -t tmpfs -o mode=777,noexec,nosuid,nodev tmp /tmp

mkdir /run/shm
mkdir /dev/shm
mount -B /run/shm /dev/shm
mkdir /dev/pts
mount -t devpts -o mode=620 pts /dev/pts

# start logging daemons
echo -n " done.
Starting logging services ..."

syslogd
logd /run/messages /var/log/messages
logd /proc/kmsg /var/log/kern.log

# run depmod, to create a cache of available kernel modules
echo -n " done.
Running depmod ..."

depmod

# start kmoduled
echo -n " done.
Starting kmoduled ..."

kmoduled

# set the hostname
echo -n " done.
Setting the hostname ..."

hostname $(cat /etc/hostname)

# configure network interfaces
echo -n " done.
Configuring networking ..."

ifconfig lo 127.0.0.1 up
route add -net 127.0.0.0 netmask 255.0.0.0 lo

# start Dropbear, with the keys under /run
echo -n " done.
Starting Dropbear ..."

mkdir /run/dropbear
for i in rsa dss
do
	dropbearkey -t $i -f /run/dropbear/${i}_key > /dev/null 2>&1
done
dropbear -d /run/dropbear/dss_key -r /run/dropbear/rsa_key

# show a login prompt
exec cttyhack sulogin
