#!/bin/dash

# set the executable search path
export PATH="/bin"

# mount virtual file systems
echo -n "Mounting virtual file systems ..."

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
mount -t tmpfs tmp /run
mkdir /run/tmp

mkdir /dev/shm
mount -t tmpfs shm /dev/shm
mkdir /dev/pts
mount -t devpts pts /dev/pts

# start logging daemons
echo -n " done.
Starting logging services ..."

syslogd
logd /run/messages /var/log/messages
logd /proc/kmsg /var/log/kern.log

# run depmod, to create a cache of available kernel modules
echo -n " done.
Running depmod ..."

depmod

# start kmoduled
echo -n " done.
Starting kmoduled ..."

kmoduled

# set the hostname
echo -n " done.
Setting the hostname ..."

hostname $(cat /etc/hostname)

# configure network interfaces
echo -n " done.
Configuring networking ..."

ifconfig lo 127.0.0.1 up
route add -net 127.0.0.0 netmask 255.0.0.0 lo

echo -n " done.
Starting Dropbear ..."

for i in rsa dss
do
	dropbearkey -t $i -f /tmp/${i}_key > /dev/null 2>&1
done
dropbear -d /tmp/dss_key -r /tmp/rsa_key

echo "done."

# show a login prompt
exec cttyhack sulogin
