#!/bin/sh

# build_initramfs: builds an initramfs archive

# files present in the initramfs
INITRAMFS_FILES="bin/toybox
                 bin/init
                 bin/ksh
                 bin/awk
                 bin/syslogd
                 bin/klogd
                 bin/mkdir
                 bin/cp
                 bin/chroot
                 bin/cttyhack
                 bin/grep
                 bin/losetup
                 bin/mount
                 bin/umount
                 bin/luufs
                 bin/fusermount
                 bin/sleep
                 bin/clear
                 bin/cat
                 bin/contain
                 bin/poweroff
                 bin/reboot
                 etc/rc.d/rc.initramfs
                 etc/rc.d/rc.shutdown"

# directories present in the initramfs
INITRAMFS_DIRECTORIES="run
                       tmp
                       etc/rc.d
                       bin
                       var/log
                       proc
                       dev
                       mnt/home
                       mnt/rw
                       mnt/union
                       mnt/ro
                       sys"


# include the configuration file
. ./config

# create a temporary directory for the initramfs contents
initramfs_root="$(mktemp -d -u)"

# create the initramfs directories
for directory in $INITRAMFS_DIRECTORIES
do
	mkdir -p "$initramfs_root/$directory"
done

# add required programs and scripts to the initramfs
for i in $INITRAMFS_FILES
do
	if [ -e "$1/$i" ]
	then
		path="$1/$i"
	else
		path="$BASE_DIR/initramfs/$i"
	fi
	cp "$path" "$initramfs_root/$i"
done

# create /dev/console
mknod -m 622 "$initramfs_root/dev/console" c 5 1

# generate an initramfs archive
kernel="$(pwd)"
cd "$initramfs_root"
chown -R 0:0 .
chmod 1777 tmp
initramfs="$(mktemp -u --suffix .cpio)"
find . | cpio -o -H newc | xz -9 -e --check=none > "$2"
rm -rf "$initramfs_root"
