#!/bin/sh

# build_rootfs: installs the RLSD root file system to a directory

# include the configuration file
. ./config

# choose which packages to install
cd flavors
. "./$1"
cd ..

# if all packages were built locally, use the build output
if [ -d "$REPO_DIR" ]
then
	repo="file://$REPO_DIR"
else
	# otherwise, use the upstream repository
	repo="http://dimkr.insomnia247.nl/$ARCH"
fi

# install the packages
mkdir -p "$2/var/packlad/downloaded" "$2/var/packlad/installed"
if [ -f "$SYSROOT/etc/packlad/pub_key" ]
then
	install -D -m 400 "$SYSROOT/etc/packlad/pub_key" "$2/etc/packlad/pub_key"
else
	install -D -m 400 /etc/packlad/pub_key "$2/etc/packlad/pub_key"
fi
REPO="$repo" packlad -p "$2" -u
for package in $PACKAGES
do
	REPO="$repo" packlad -s -i $package -n -p "$2"
done

# clean up after packlad
rm -vf "$2/var/packlad/available" "$2/var/packlad/downloaded"/*

# fix permissions
chown -R 0:0 "$2"
find "$2" -type d | while read directory
do
	chmod 755 "$directory"
done
chmod 700 "$2/home/boss"
chown 1000:1000 "$2/home/someone"
chmod 755 "$2/home/someone"
