PACKAGE_VERSION="0.4.5"
PACKAGE_SOURCES="http://www.landley.net/toybox/downloads/toybox-$PACKAGE_VERSION.tar.bz2"

toybox_build() {
	[ -d toybox-$PACKAGE_VERSION ] && rm -rf toybox-$PACKAGE_VERSION
	tar -xjvf toybox-$PACKAGE_VERSION.tar.bz2
	cd toybox-$PACKAGE_VERSION

	cat << EOF > .config
#
# Automatically generated make config: don't edit
# ToyBox version: KCONFIG_VERSION
# Fri Sep  6 14:19:18 2013
#
CONFIG_TOYBOX_CONTAINER=y

#
# LSB commands
#
CONFIG_DMESG=y
CONFIG_HOSTNAME=y
CONFIG_KILLALL=y
CONFIG_MD5SUM=y
CONFIG_MD5SUM_SHA1SUM=y
CONFIG_MKNOD=y
CONFIG_MKTEMP=y
CONFIG_PASSWD=y
CONFIG_PIDOF=y
CONFIG_SEQ=y
CONFIG_SYNC=y

#
# Other commands
#
CONFIG_BZCAT=y
CONFIG_CATV=y
CONFIG_CHROOT=y
CONFIG_CHVT=y
CONFIG_CLEAR=y
CONFIG_COUNT=y
CONFIG_DOS2UNIX=y
CONFIG_FREE=y
# CONFIG_HELLO is not set
CONFIG_HELP=y
CONFIG_INSMOD=y
CONFIG_LOGIN=y
CONFIG_LOSETUP=y
CONFIG_LSMOD=y
CONFIG_LSUSB=y
CONFIG_MKSWAP=y
CONFIG_MODINFO=y
CONFIG_MOUNTPOINT=y
CONFIG_NETCAT=y
CONFIG_NETCAT_LISTEN=y
CONFIG_ONEIT=y
CONFIG_PIVOT_ROOT=y
CONFIG_PRINTENV=y
CONFIG_READAHEAD=y
CONFIG_READLINK=y
CONFIG_REALPATH=y
CONFIG_REV=y
CONFIG_RMMOD=y
CONFIG_SETSID=y
CONFIG_STAT=y
CONFIG_SWAPOFF=y
CONFIG_SWAPON=y
CONFIG_SWITCH_ROOT=y
CONFIG_TAC=y
CONFIG_TASKSET=y
CONFIG_TRUNCATE=y
CONFIG_UNSHARE=y
CONFIG_UPTIME=y
CONFIG_USLEEP=y
CONFIG_VCONFIG=y
CONFIG_VMSTAT=y
CONFIG_W=y
CONFIG_WHICH=y
CONFIG_WHOAMI=y
CONFIG_YES=y

#
# pending
#
CONFIG_EXPR=y
CONFIG_FIND=y
CONFIG_IFCONFIG=y
CONFIG_LOGGER=y
# CONFIG_MDEV is not set
# CONFIG_MDEV_CONF is not set
# CONFIG_MKE2FS is not set
# CONFIG_MKE2FS_JOURNAL is not set
# CONFIG_MKE2FS_GEN is not set
# CONFIG_MKE2FS_LABEL is not set
# CONFIG_MKE2FS_EXTENDED is not set
# CONFIG_NBD_CLIENT is not set
CONFIG_SED=y
# CONFIG_SH is not set
# CONFIG_SH_TTY is not set
# CONFIG_SH_PROFILE is not set
# CONFIG_SH_JOBCTL is not set
# CONFIG_SH_FLOWCTL is not set
# CONFIG_SH_QUOTES is not set
# CONFIG_SH_WILDCARDS is not set
# CONFIG_SH_PROCARGS is not set
# CONFIG_SH_ENVVARS is not set
# CONFIG_SH_LOCALS is not set
# CONFIG_SH_ARRAYS is not set
# CONFIG_SH_PIPES is not set
# CONFIG_SH_BUILTINS is not set
# CONFIG_EXIT is not set
# CONFIG_CD is not set
# CONFIG_CD_P is not set
CONFIG_TEST=y
# CONFIG_XZCAT is not set

#
# Posix commands
#
CONFIG_BASENAME=y
CONFIG_CAL=y
CONFIG_CAT=y
CONFIG_CHGRP=y
CONFIG_CHMOD=y
CONFIG_CKSUM=y
CONFIG_CMP=y
CONFIG_COMM=y
CONFIG_CP=y
CONFIG_CP_MORE=y
CONFIG_CP_MV=y
CONFIG_CUT=y
CONFIG_DATE=y
CONFIG_DF=y
CONFIG_DF_PEDANTIC=y
CONFIG_DIRNAME=y
CONFIG_DU=y
CONFIG_ECHO=y
CONFIG_ENV=y
CONFIG_EXPAND=y
CONFIG_FALSE=y
CONFIG_HEAD=y
CONFIG_ID=y
CONFIG_ID_GROUPS=y
CONFIG_KILL=y
CONFIG_LINK=y
CONFIG_LN=y
CONFIG_LOGNAME=y
CONFIG_LS=y
CONFIG_LS_COLOR=y
CONFIG_MKDIR=y
CONFIG_MKFIFO=y
CONFIG_NICE=y
CONFIG_NOHUP=y
CONFIG_OD=y
CONFIG_PATCH=y
CONFIG_PWD=y
CONFIG_RM=y
CONFIG_RMDIR=y
CONFIG_SLEEP=y
CONFIG_SLEEP_FLOAT=y
CONFIG_SORT=y
CONFIG_SORT_BIG=y
CONFIG_SORT_FLOAT=y
CONFIG_SPLIT=y
CONFIG_TAIL=y
CONFIG_TAIL_SEEK=y
CONFIG_TEE=y
CONFIG_TIME=y
CONFIG_TOUCH=y
CONFIG_TRUE=y
CONFIG_TTY=y
CONFIG_UNAME=y
CONFIG_UNIQ=y
CONFIG_UNLINK=y
CONFIG_UUDECODE=y
CONFIG_UUENCODE=y
CONFIG_WC=y
CONFIG_WHO=y
CONFIG_XARGS=y

#
#
#

#
# Toybox global settings
#
# CONFIG_TOYBOX is not set
# CONFIG_TOYBOX_SUID is not set
CONFIG_TOYBOX_FLOAT=y
CONFIG_TOYBOX_HELP=y
CONFIG_TOYBOX_HELP_DASHDASH=y
# CONFIG_TOYBOX_I18N is not set
# CONFIG_TOYBOX_FREE is not set
# CONFIG_TOYBOX_DEBUG is not set
EOF

	CC="$CC" STRIP="$STIRP" make
}

toybox_package() {
	sed s~'--long'~''~g -i scripts/install.sh
	make PREFIX="$1/bin" install
	install -D -m 644 README "$1/usr/share/doc/toybox/README"
	install -D -m 644 LICENSE "$1/usr/share/doc/toybox/LICENSE"
}
