PACKAGE_VERSION="0.4.9"
PACKAGE_SOURCES="http://www.landley.net/toybox/downloads/toybox-$PACKAGE_VERSION.tar.bz2"
PACKAGE_DESC="System tools"

toybox_build() {
	[ -d toybox-$PACKAGE_VERSION ] && rm -rf toybox-$PACKAGE_VERSION
	tar -xjvf toybox-$PACKAGE_VERSION.tar.bz2
	cd toybox-$PACKAGE_VERSION

	cat << EOF > .config
#
# Automatically generated make config: don't edit
# ToyBox version: KCONFIG_VERSION
# Wed Jul  9 21:36:41 2014
#
CONFIG_TOYBOX_CONTAINER=y
CONFIG_TOYBOX_FIFREEZE=y
CONFIG_TOYBOX_ICONV=y
CONFIG_TOYBOX_FALLOCATE=y

#
# Posix commands
#
CONFIG_BASENAME=y
CONFIG_CAL=y
CONFIG_CAT=y
CONFIG_CHGRP=y
CONFIG_CHMOD=y
CONFIG_CKSUM=y
# CONFIG_CMP is not set
CONFIG_COMM=y
CONFIG_CP=y
CONFIG_CP_MORE=y
CONFIG_CP_MV=y
CONFIG_CP_MV_MORE=y
# CONFIG_CPIO is not set
CONFIG_CUT=y
CONFIG_DATE=y
CONFIG_DF=y
CONFIG_DF_PEDANTIC=y
CONFIG_DIRNAME=y
CONFIG_DU=y
CONFIG_ECHO=y
CONFIG_ENV=y
CONFIG_EXPAND=y
CONFIG_FALSE=y
CONFIG_GREP=y
CONFIG_HEAD=y
CONFIG_ID=y
CONFIG_ID_GROUPS=y
CONFIG_ID_LOGNAME=y
CONFIG_KILL=y
CONFIG_KILLALL5=y
CONFIG_LINK=y
CONFIG_LN=y
CONFIG_LS=y
CONFIG_LS_COLOR=y
CONFIG_MKDIR=y
CONFIG_MKFIFO=y
CONFIG_NICE=y
CONFIG_NL=y
CONFIG_NOHUP=y
CONFIG_OD=y
CONFIG_PASTE=y
# CONFIG_PATCH is not set
CONFIG_PWD=y
CONFIG_RENICE=y
CONFIG_RM=y
CONFIG_RMDIR=y
CONFIG_SLEEP=y
CONFIG_SLEEP_FLOAT=y
CONFIG_SORT=y
CONFIG_SORT_BIG=y
CONFIG_SORT_FLOAT=y
CONFIG_SPLIT=y
CONFIG_STRINGS=y
CONFIG_TAIL=y
CONFIG_TAIL_SEEK=y
CONFIG_TEE=y
CONFIG_TIME=y
CONFIG_TOUCH=y
CONFIG_TRUE=y
# CONFIG_TTY is not set
CONFIG_UNAME=y
CONFIG_UNIQ=y
# CONFIG_UNLINK is not set
CONFIG_UUDECODE=y
CONFIG_UUENCODE=y
CONFIG_WC=y
CONFIG_WHO=y
CONFIG_XARGS=y
# CONFIG_XARGS_PEDANTIC is not set

#
# pending
#
CONFIG_ARP=y
CONFIG_ARPING=y
# CONFIG_BOOTCHARTD is not set
CONFIG_BRCTL=y
# CONFIG_COMPRESS is not set
# CONFIG_ZCAT is not set
CONFIG_DD=y
# CONFIG_DHCP is not set
# CONFIG_DHCPD is not set
# CONFIG_DEBUG_DHCP is not set
# CONFIG_DUMPLEASES is not set
CONFIG_EXPR=y
CONFIG_FDISK=y
CONFIG_FIND=y
CONFIG_FOLD=y
CONFIG_FSCK=y
CONFIG_FTPGET=y
# CONFIG_GETTY is not set
# CONFIG_GROUPADD is not set
# CONFIG_GROUPDEL is not set
# CONFIG_HOST is not set
# CONFIG_ICONV is not set
# CONFIG_INIT is not set
# CONFIG_INOTIFYD is not set
# CONFIG_KLOGD is not set
# CONFIG_KLOGD_SOURCE_RING_BUFFER is not set
CONFIG_LAST=y
# CONFIG_LOGGER is not set
CONFIG_LSPCI=y
# CONFIG_LSPCI_TEXT is not set
# CONFIG_MDEV is not set
# CONFIG_MDEV_CONF is not set
CONFIG_MKE2FS=y
CONFIG_MKE2FS_JOURNAL=y
# CONFIG_MKE2FS_GEN is not set
CONFIG_MKE2FS_LABEL=y
CONFIG_MKE2FS_EXTENDED=y
# CONFIG_MODPROBE is not set
CONFIG_MORE=y
# CONFIG_MOUNT is not set
# CONFIG_NBD_CLIENT is not set
CONFIG_NETSTAT=y
# CONFIG_OPENVT is not set
# CONFIG_DEALLOCVT is not set
CONFIG_PGREP=y
CONFIG_PRINTF=y
CONFIG_PS=y
CONFIG_RESET=y
CONFIG_ROUTE=y
CONFIG_SED=y
# CONFIG_SH is not set
# CONFIG_SH_INTERACTIVE is not set
# CONFIG_EXIT is not set
# CONFIG_CD is not set
# CONFIG_SULOGIN is not set
# CONFIG_SYSLOGD is not set
# CONFIG_TAR is not set
# CONFIG_TCPSVD is not set
CONFIG_TELNET=y
# CONFIG_TELNETD is not set
CONFIG_TEST=y
# CONFIG_TFTPD is not set
CONFIG_TOP=y
CONFIG_TRACEROUTE=y
# CONFIG_USERADD is not set
CONFIG_WATCH=y
# CONFIG_XZCAT is not set

#
# Other commands
#
CONFIG_ACPI=y
CONFIG_BLKID=y
# CONFIG_BZCAT is not set
CONFIG_CATV=y
CONFIG_CHROOT=y
# CONFIG_CHVT is not set
CONFIG_CLEAR=y
CONFIG_COUNT=y
CONFIG_DOS2UNIX=y
CONFIG_EJECT=y
# CONFIG_FALLOCATE is not set
CONFIG_FREE=y
CONFIG_FREERAMDISK=y
CONFIG_FSFREEZE=y
# CONFIG_HELP is not set
# CONFIG_HELP_EXTRAS is not set
CONFIG_IFCONFIG=y
# CONFIG_INSMOD is not set
CONFIG_LOGIN=y
# CONFIG_LOSETUP is not set
CONFIG_LSATTR=y
CONFIG_CHATTR=y
# CONFIG_LSMOD is not set
CONFIG_LSUSB=y
# CONFIG_MAKEDEVS is not set
CONFIG_MKPASSWD=y
CONFIG_MKSWAP=y
# CONFIG_MODINFO is not set
CONFIG_MOUNTPOINT=y
# CONFIG_NETCAT is not set
# CONFIG_NETCAT_LISTEN is not set
# CONFIG_ONEIT is not set
CONFIG_PARTPROBE=y
CONFIG_PIVOT_ROOT=y
CONFIG_PMAP=y
CONFIG_PRINTENV=y
CONFIG_PWDX=y
CONFIG_READAHEAD=y
CONFIG_READLINK=y
CONFIG_REALPATH=y
# CONFIG_REBOOT is not set
CONFIG_REV=y
# CONFIG_RFKILL is not set
# CONFIG_RMMOD is not set
CONFIG_SETSID=y
CONFIG_STAT=y
CONFIG_SWAPOFF=y
CONFIG_SWAPON=y
CONFIG_SWITCH_ROOT=y
CONFIG_SYSCTL=y
CONFIG_TAC=y
CONFIG_TASKSET=y
CONFIG_TIMEOUT=y
CONFIG_TRUNCATE=y
# CONFIG_UNSHARE is not set
CONFIG_UPTIME=y
CONFIG_USLEEP=y
CONFIG_VCONFIG=y
CONFIG_VMSTAT=y
CONFIG_W=y
CONFIG_WHICH=y
CONFIG_YES=y

#
# Linux Standard Base commands
#
CONFIG_DMESG=y
CONFIG_HOSTNAME=y
CONFIG_KILLALL=y
CONFIG_MD5SUM=y
# CONFIG_MD5SUM_SHA1SUM is not set
CONFIG_MKNOD=y
CONFIG_MKTEMP=y
CONFIG_PASSWD=y
CONFIG_PIDOF=y
CONFIG_SEQ=y
CONFIG_SU=y
CONFIG_SYNC=y
# CONFIG_UMOUNT is not set

#
# Example commands
#
# CONFIG_HELLO is not set
# CONFIG_SKELETON is not set
# CONFIG_SKELETON_ALIAS is not set

#
#
#

#
# Toybox global settings
#
CONFIG_TOYBOX=y
CONFIG_TOYBOX_SUID=y
CONFIG_TOYBOX_FLOAT=y
CONFIG_TOYBOX_HELP=y
CONFIG_TOYBOX_HELP_DASHDASH=y
# CONFIG_TOYBOX_I18N is not set
# CONFIG_TOYBOX_FREE is not set
# CONFIG_TOYBOX_DEBUG is not set
EOF

	OPTIMIZE=" " $MAKE
}

toybox_package() {
	$MAKE PREFIX="$1/bin" install_flat
	install -D -m 644 README "$1/usr/share/doc/toybox/README"
	install -m 644 LICENSE "$1/usr/share/doc/toybox/LICENSE"
}
